# add these lines to /root/.bash_profile
export MAKEFLAGS=-j7
source /sources/lc_autolfs/s_f
# invoke autolfs from the .cmds directory to go straight to install without cd
function autolfs {
	cd ..
	./install.sh
	if [[ $? = 0 ]]; then popd; fi
}
echo "hello worlds"
